require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - '.simplecov'
    - 'spec/tmp/**/*'
    - 'spec/dummy/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/RakeEnvironment:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/dummy/db/migrate/**/*'

Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'
