name: Codecov

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      CODECOV: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: rake spec